@baseUrl = http://localhost:9000/api/v1/role
###
GET {{baseUrl}}
###
GET {{baseUrl}}/1
###
POST {{baseUrl}}
Content-Type: application/json

{
  "name" : "role 3"
  ,
  "privileges" : [
    {
      "id" : 1
    },
    {
      "id" : 2
    }
  ]
}
###
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name" : "role 1 update"
  ,
  "privileges" : [
    {
      "id" : 1
    }
    ,
    {
      "id" : 2
    }
  ]
}
###
DELETE {{baseUrl}}/1