@baseUrl = http://localhost:9000/api/v1/user
###
GET {{baseUrl}}
###
GET {{baseUrl}}/1
###
POST {{baseUrl}}
Content-Type: application/json

{
  "username" : "8baru",
  "password" : "8baru",
  "name" : "8baru",
  "email" : "8baru@mail.com",
  "phone" : "8baru",
  "salary" : 1.23,
  "managerId" : 1
  # ,
  # "roles" : [
  #   {
  #     "id" : 2
  #   },
  #   {
  #     "id" : 3
  #   }
  # ]
}
###
PUT {{baseUrl}}/7
Content-Type: application/json

{
  "username" : "5baru",
  "password" : "5baru",
  "name" : "5baru",
  "email" : "5baru@mail.com",
  "phone" : "5baru",
  "salary" : 1.23,
  "managerId" : 1
  ,
  "roles" : [
    {
      "id" : 2
    },
    {
      "id" : 4
    }
  ]
}
###
DELETE {{baseUrl}}/12